version: '2'
plugins:
  eslint:
    enabled: true
    config:
      config: .eslintrc.json
      extensions:
        - .js
        - .jsx
      checks:
        import/extensions:
          enabled: false
        prettier/prettier:
          enabled: false
