plugins:
  eslint:
    enabled: true
    config:
      config: .eslintrc.json
  eslint-config-prettier:
    enabled: true
  eslint-plugin-import:
    enabled: true
  eslint-plugin-jsx-a11y:
    enabled: true
  eslint-plugin-prettier:
    enabled: true
  eslint-plugin-react:
    enabled: true
